version: '3.3'

services:
  source-kafka-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: source-kafka-api
    networks:
      - scdf_default

networks:
  scdf_default:
    external: true
