version: '3'

services:
  localkafka:
    image: wurstmeister/kafka
    container_name: localkafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=OUTSIDE://localkafka:9092,INSIDE://localhost:9093
      - KAFKA_ADVERTISED_LISTENERS=OUTSIDE://localkafka:9092,INSIDE://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=OUTSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - scdf_default

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - scdf_default

networks:
  scdf_default:
    external: true
